#!/bin/sh
set -e
cd /Users/user/microbiz/microbiz-os

cat > database/seeders/GlAccountSeeder.php << 'MBOS_EOF'
<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\GlAccount;

class GlAccountSeeder extends Seeder
{
    public function run(): void
    {
        $accounts = [
            [
                'fineract_gl_id' => 100100,
                'gl_code' => '100100',
                'name' => 'Interest Income (Placeholder)',
                'type' => 'INCOME',
                'usage' => 'INTEREST_INCOME',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 111156,
                'gl_code' => '1-11-156',
                'name' => 'Commission on Electronic Funds Transfer',
                'type' => 'INCOME',
                'usage' => 'TRANSFER_FEE',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 100120,
                'gl_code' => '100120',
                'name' => 'Withdrawal Fee Income (Placeholder)',
                'type' => 'INCOME',
                'usage' => 'WITHDRAWAL_FEE',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 111150,
                'gl_code' => '1-11-150',
                'name' => 'COMMISSION',
                'type' => 'INCOME',
                'usage' => 'COMMISSION_INCOME',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 211002,
                'gl_code' => '2-11-002',
                'name' => 'Basic Salaries',
                'type' => 'EXPENSE',
                'usage' => 'SALARY_EXPENSE',
                'manual_entries_allowed' => true,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 211208,
                'gl_code' => '2-11-208',
                'name' => 'Office & General Expenses',
                'type' => 'EXPENSE',
                'usage' => 'OFFICE_EXPENSE',
                'manual_entries_allowed' => true,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 200120,
                'gl_code' => '200120',
                'name' => 'Utility Expense (Placeholder)',
                'type' => 'EXPENSE',
                'usage' => 'UTILITY_EXPENSE',
                'manual_entries_allowed' => true,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 211291,
                'gl_code' => '2-11-291',
                'name' => 'Cash Specie Expenses',
                'type' => 'EXPENSE',
                'usage' => 'CASH_HANDLING_EXPENSE',
                'manual_entries_allowed' => true,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 211100,
                'gl_code' => '2-11-100',
                'name' => 'Interest Expense (General)',
                'type' => 'EXPENSE',
                'usage' => 'INTEREST_EXPENSE',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 211133,
                'gl_code' => '2-11-133',
                'name' => 'Int Exp- Fixed Dep(60 Dys)',
                'type' => 'EXPENSE',
                'usage' => 'INTEREST_EXPENSE_FD_60',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 211134,
                'gl_code' => '2-11-134',
                'name' => 'Int Exp - Fixed Dep(90 Dys)',
                'type' => 'EXPENSE',
                'usage' => 'INTEREST_EXPENSE_FD_90',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 211135,
                'gl_code' => '2-11-135',
                'name' => 'Int Exp- Fixed Dep(180 Dys)',
                'type' => 'EXPENSE',
                'usage' => 'INTEREST_EXPENSE_FD_180',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 211136,
                'gl_code' => '2-11-136',
                'name' => 'Int Exp - Fixed Dep(270 Dys)',
                'type' => 'EXPENSE',
                'usage' => 'INTEREST_EXPENSE_FD_270',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 211137,
                'gl_code' => '2-11-137',
                'name' => 'Int Exp - Fixed Dep(365 Dys)',
                'type' => 'EXPENSE',
                'usage' => 'INTEREST_EXPENSE_FD_365',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 3001700,
                'gl_code' => '300170',
                'name' => 'Cash Control',
                'type' => 'ASSET',
                'usage' => 'CASH_CONTROL',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 313998,
                'gl_code' => '3-13-998',
                'name' => 'Cash At Vault',
                'type' => 'ASSET',
                'usage' => 'VAULT_CASH',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 313999,
                'gl_code' => '3-13-999',
                'name' => 'Cash At Teller',
                'type' => 'ASSET',
                'usage' => 'TELLER_CASH',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 313465,
                'gl_code' => '3-13-465',
                'name' => 'Transit Account',
                'type' => 'ASSET',
                'usage' => 'CASH_IN_TRANSIT',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 300140,
                'gl_code' => '300140',
                'name' => 'ATM Cash (Placeholder)',
                'type' => 'ASSET',
                'usage' => 'ATM_CASH',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 300150,
                'gl_code' => '300150',
                'name' => 'Treasury Vault (Placeholder)',
                'type' => 'ASSET',
                'usage' => 'TREASURY_VAULT',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 300160,
                'gl_code' => '300160',
                'name' => 'Interbranch Settlement (Placeholder)',
                'type' => 'ASSET',
                'usage' => 'INTERBRANCH_SETTLEMENT',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 300170,
                'gl_code' => '300170',
                'name' => 'Suspense Asset (Placeholder)',
                'type' => 'ASSET',
                'usage' => 'SUSPENSE_ASSET',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400147,
                'gl_code' => '4-00-147',
                'name' => 'Regular Savings Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_REGULAR',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400148,
                'gl_code' => '4-00-148',
                'name' => 'Kids Savings',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_KIDS',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400149,
                'gl_code' => '4-00-149',
                'name' => 'MASTA Savings Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_MASTA',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400150000,
                'gl_code' => '4-00-150',
                'name' => 'MYBIZ Savings Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_MYBIZ',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400151,
                'gl_code' => '4-00-151',
                'name' => 'Active Savings Account',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_ACTIVE',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400152,
                'gl_code' => '4-00-152',
                'name' => 'Education Savings Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_EDUCATION',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400153,
                'gl_code' => '4-00-153',
                'name' => 'Group Savings Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_GROUP',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400154,
                'gl_code' => '4-00-154',
                'name' => 'Salary Savings Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_SALARY',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400155,
                'gl_code' => '4-00-155',
                'name' => 'Savings Corporate Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_CORPORATE',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400156,
                'gl_code' => '4-00-156',
                'name' => 'MyKonnect Savings',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_MYKONNECT',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400157,
                'gl_code' => '4-00-157',
                'name' => 'Peak Daily Savings',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_PEAK_DAILY',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400158,
                'gl_code' => '4-00-158',
                'name' => 'Peak Group Savings',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_PEAK_GROUP',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400160000,
                'gl_code' => '4-00-160',
                'name' => 'Peak Salary Saving',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_PEAK_SALARY',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400161,
                'gl_code' => '4-00-161',
                'name' => 'Peak Traders Savings',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_PEAK_TRADERS',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400163,
                'gl_code' => '4-00-163',
                'name' => 'MicroFlex Target Savings Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_MICROFLEX',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400166,
                'gl_code' => '4-00-166',
                'name' => 'YES ACCOUNT (Youth Enterprise Savings)',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_SAVINGS_YES',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400107,
                'gl_code' => '4-00-107',
                'name' => 'Individual Current Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_CURRENT_INDIVIDUAL',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400108,
                'gl_code' => '4-00-108',
                'name' => 'Corporate Current',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_CURRENT_CORPORATE',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400109,
                'gl_code' => '4-00-109',
                'name' => 'Salary Current Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_CURRENT_SALARY',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400110000,
                'gl_code' => '4-00-110',
                'name' => 'Staff Current Acct',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_CURRENT_STAFF',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400214,
                'gl_code' => '4-00-214',
                'name' => 'Fixed Deposits 60 Days',
                'type' => 'LIABILITY',
                'usage' => 'FIXED_DEPOSIT_60',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400215,
                'gl_code' => '4-00-215',
                'name' => 'Fixed Deposits 90 Days',
                'type' => 'LIABILITY',
                'usage' => 'FIXED_DEPOSIT_90',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400216,
                'gl_code' => '4-00-216',
                'name' => 'Fixed Deposits 180 Days',
                'type' => 'LIABILITY',
                'usage' => 'FIXED_DEPOSIT_180',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400217,
                'gl_code' => '4-00-217',
                'name' => 'Fixed Deposits 270 Days',
                'type' => 'LIABILITY',
                'usage' => 'FIXED_DEPOSIT_270',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400218,
                'gl_code' => '4-00-218',
                'name' => 'Fixed Deposits 365 Days',
                'type' => 'LIABILITY',
                'usage' => 'FIXED_DEPOSIT_365',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400130,
                'gl_code' => '400130',
                'name' => 'Wallet Liability (Placeholder)',
                'type' => 'LIABILITY',
                'usage' => 'WALLET_LIABILITY',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400140,
                'gl_code' => '400140',
                'name' => 'Agency Float (Placeholder)',
                'type' => 'LIABILITY',
                'usage' => 'AGENCY_FLOAT',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400150,
                'gl_code' => '400150',
                'name' => 'Teller Over / Short',
                'type' => 'LIABILITY',
                'usage' => 'TELLER_OVER_SHORT',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400160,
                'gl_code' => '400160',
                'name' => 'Suspense Liability (Placeholder)',
                'type' => 'LIABILITY',
                'usage' => 'SUSPENSE_LIABILITY',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400170,
                'gl_code' => '400170',
                'name' => 'Merchant Settlement Liability (Placeholder)',
                'type' => 'LIABILITY',
                'usage' => 'MERCHANT_LIABILITY',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400180,
                'gl_code' => '400180',
                'name' => 'Customer Deposit Control (Internal)',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_DEPOSIT_CONTROL',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 400190,
                'gl_code' => '400190',
                'name' => 'Customer Withdrawal Control (Internal)',
                'type' => 'LIABILITY',
                'usage' => 'CUSTOMER_WITHDRAWAL_CONTROL',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 500001,
                'gl_code' => '5-00-001',
                'name' => 'Paid Up Capital',
                'type' => 'EQUITY',
                'usage' => 'SHARE_CAPITAL',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 500045,
                'gl_code' => '5-00-045',
                'name' => 'Retained Earnings P/L',
                'type' => 'EQUITY',
                'usage' => 'RETAINED_EARNINGS',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
            [
                'fineract_gl_id' => 500120,
                'gl_code' => '500120',
                'name' => 'Current Year Earnings (Placeholder)',
                'type' => 'EQUITY',
                'usage' => 'CURRENT_YEAR_EARNINGS',
                'manual_entries_allowed' => false,
                'disabled' => false,
            ],
        ];

        foreach ($accounts as $account) {

            GlAccount::updateOrCreate(
                [
                    'usage' => $account['usage'],
                ],
                [
                    'fineract_gl_id' => $account['fineract_gl_id'],
                    'gl_code' => $account['gl_code'],
                    'name' => $account['name'],
                    'type' => $account['type'],
                    'manual_entries_allowed' => $account['manual_entries_allowed'],
                    'disabled' => $account['disabled'],
                ]
            );

        }
    }
}
MBOS_EOF

echo "Part 2 of 4 applied (GlAccountSeeder.php)."