import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { MerchantPortalApiService } from '../../core/merchant-portal-api.service';
import { MerchantNotification, MerchantNotificationPreferences, MerchantSecuritySummary } from '../../core/models/merchant-portal.models';

@Component({
  selector: 'app-merchant-settings',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section class="settings-page">
      <header><p>Account controls</p><h1>Notifications & security</h1><span>Choose how MicroBiz contacts you and protect your merchant workspace.</span></header>
      <nav class="tabs"><button [class.active]="activeTab() === 'notifications'" (click)="activeTab.set('notifications')">Notifications <span>{{ unreadCount }}</span></button><button [class.active]="activeTab() === 'security'" (click)="activeTab.set('security')">Security</button></nav>
      @if (loading()) { <div class="state-card">Loading settings…</div> }
      @else if (error()) { <div class="state-card error"><strong>Settings unavailable</strong><p>{{ error() }}</p><button (click)="load()">Try again</button></div> }
      @else if (activeTab() === 'notifications') {
        <div class="settings-layout"><section class="panel"><div class="panel-heading"><div><h2>Recent notifications</h2><p>Payment, settlement, device, and security updates.</p></div></div>@if (notifications().length === 0) { <div class="empty">You have no notifications.</div> } @else { <div class="notification-list">@for (notification of notifications(); track notification.id) { <button type="button" [class.unread]="!notification.read" (click)="readNotification(notification)"><span [class]="'notification-icon notification-icon--' + notification.type.toLowerCase()">{{ notificationIcon(notification.type) }}</span><div><strong>{{ notification.title }}</strong><p>{{ notification.message }}</p><small>{{ notification.createdAt | date:'medium' }}</small></div>@if (!notification.read) { <i></i> }</button> }</div> }</section><section class="panel preferences"><div class="panel-heading"><div><h2>Delivery preferences</h2><p>Select the channels used for important updates.</p></div></div><form (ngSubmit)="savePreferences()"><label><span><strong>Email notifications</strong><small>Statements, security, and account notices</small></span><input type="checkbox" name="emailPreference" [(ngModel)]="preferences.email" /></label><label><span><strong>SMS notifications</strong><small>Payments, settlements, and urgent alerts</small></span><input type="checkbox" name="smsPreference" [(ngModel)]="preferences.sms" /></label><label><span><strong>Push notifications</strong><small>Real-time portal and device activity</small></span><input type="checkbox" name="pushPreference" [(ngModel)]="preferences.push" /></label><label><span><strong>WhatsApp notifications</strong><small>Optional business account updates</small></span><input type="checkbox" name="whatsappPreference" [(ngModel)]="preferences.whatsapp" /></label>@if (preferenceSuccess()) { <div class="success">✓ Notification preferences saved.</div> }<button class="primary" type="submit" [disabled]="savingPreferences()">{{ savingPreferences() ? 'Saving…' : 'Save preferences' }}</button></form></section></div>
      } @else if (security(); as accountSecurity) {
        <div class="security-layout"><section class="panel"><div class="panel-heading"><div><h2>Password</h2><p>Use a strong password you do not reuse elsewhere.</p></div>@if (accountSecurity.lastPasswordChange) { <span>Last changed {{ accountSecurity.lastPasswordChange | date:'dd MMM yyyy' }}</span> }</div><form class="password-form" (ngSubmit)="changePassword()" #passwordForm="ngForm"><label>Current password<input type="password" name="currentPassword" [(ngModel)]="password.current" required autocomplete="current-password" /></label><label>New password<input type="password" name="newPassword" [(ngModel)]="password.next" required minlength="8" autocomplete="new-password" /></label><label>Confirm new password<input type="password" name="confirmPassword" [(ngModel)]="password.confirm" required minlength="8" autocomplete="new-password" /></label>@if (securityError()) { <div class="form-error">{{ securityError() }}</div> }@if (passwordSuccess()) { <div class="success">✓ Your password was updated.</div> }<button class="primary" type="submit" [disabled]="passwordForm.invalid || savingPassword()">{{ savingPassword() ? 'Updating password…' : 'Update password' }}</button></form></section><section class="panel security-summary"><div class="security-icon">◆</div><h2>Two-step verification</h2><p>Add a second verification step when signing in to your merchant account.</p><div class="security-status"><span>Status</span><strong [class.enabled]="accountSecurity.mfaEnabled">{{ accountSecurity.mfaEnabled ? 'Enabled' : 'Not enabled' }}</strong></div><button class="primary" type="button" (click)="openMfaFlow()" [disabled]="savingMfa()">{{ savingMfa() ? 'Updating…' : accountSecurity.mfaEnabled ? 'Disable two-step verification' : 'Enable two-step verification' }}</button><hr /><div class="session-row"><span>Active sessions</span><strong>{{ accountSecurity.activeSessionCount }}</strong></div><small>Signing out removes the current session. A future backend update will support revoking other devices individually.</small></section></div>
      }
      @if (showMfaModal()) { <div class="modal-backdrop"><section class="mfa-modal"><h2>{{ security()?.mfaEnabled ? 'Disable two-step verification' : 'Verify your phone' }}</h2><p>{{ security()?.mfaEnabled ? 'Enter your current password to remove the additional sign-in step.' : 'A verification code was sent to ' + mfaDestination() + '. Use 0000 while this feature is mocked.' }}</p><form (ngSubmit)="confirmMfa()" #mfaForm="ngForm">@if (security()?.mfaEnabled) { <label>Current password<input type="password" name="mfaPassword" [(ngModel)]="mfaPassword" required /></label> } @else { <label>Verification code<input name="mfaCode" [(ngModel)]="mfaCode" required pattern="[0-9]{4,6}" inputmode="numeric" /></label> }@if (securityError()) { <div class="form-error">{{ securityError() }}</div> }<div class="mfa-actions"><button type="button" class="secondary" (click)="closeMfaModal()">Cancel</button><button type="submit" class="primary" [disabled]="mfaForm.invalid || savingMfa()">{{ savingMfa() ? 'Confirming…' : 'Confirm' }}</button></div></form></section></div> }
    </section>
  `,
  styles: [`
    .settings-page { display: grid; gap: 1.25rem; max-width: 1150px; }header p { text-transform: uppercase; color: #a06e00; letter-spacing: .11em; font-size: .7rem; font-weight: 800; margin: 0; }header h1 { color: #182250; font-size: 2rem; letter-spacing: -.04em; margin: .25rem 0; }header span { color: #7e8497; font-size: .85rem; }.tabs { display: flex; gap: .35rem; border-bottom: 1px solid #dfe3ec; }.tabs button { border: 0; background: transparent; padding: .75rem .85rem; color: #757c90; font-weight: 700; border-bottom: 2px solid transparent; }.tabs button.active { color: #1e2761; border-bottom-color: #1e2761; }.tabs span { margin-left: .3rem; padding: .15rem .35rem; border-radius: 1rem; background: #e9ecf5; font-size: .65rem; }
    .settings-layout, .security-layout { display: grid; grid-template-columns: 1.25fr .75fr; gap: 1rem; align-items: start; }.panel { background: #fff; border: 1px solid #dfe3ec; border-radius: .8rem; overflow: hidden; }.panel-heading { display: flex; justify-content: space-between; gap: 1rem; padding: 1rem 1.15rem; border-bottom: 1px solid #e9ecf2; }.panel-heading h2, .security-summary h2 { margin: 0 0 .25rem; color: #303950; font-size: 1rem; }.panel-heading p { margin: 0; color: #8b91a3; font-size: .7rem; }.panel-heading > span { color: #8c92a3; font-size: .62rem; }.notification-list button { width: 100%; display: grid; grid-template-columns: auto 1fr auto; gap: .75rem; text-align: left; padding: .9rem 1.1rem; border: 0; border-bottom: 1px solid #eceef3; background: #fff; }.notification-list button.unread { background: #f8f9ff; }.notification-icon { width: 2.2rem; height: 2.2rem; display: grid; place-items: center; border-radius: .55rem; background: #edf0fb; color: #304b9c; }.notification-icon--security { background: #fff2ce; color: #936400; }.notification-icon--settlement { background: #e3f5eb; color: #23754e; }.notification-list div { display: grid; gap: .18rem; }.notification-list strong { color: #333c53; font-size: .76rem; }.notification-list p { margin: 0; color: #747b8f; font-size: .69rem; }.notification-list small { color: #999eae; font-size: .61rem; }.notification-list i { width: .45rem; height: .45rem; border-radius: 50%; background: #4057ad; }.empty { min-height: 220px; display: grid; place-content: center; color: #858b9c; }
    .preferences form { display: grid; padding: .3rem 1.15rem 1.15rem; }.preferences label { display: flex; justify-content: space-between; align-items: center; gap: 1rem; padding: .85rem 0; border-bottom: 1px solid #eceef3; }.preferences label span { display: grid; gap: .2rem; }.preferences label strong { color: #444d64; font-size: .73rem; }.preferences label small { color: #969cad; font-size: .62rem; }.preferences input { width: 1.05rem; height: 1.05rem; }.primary, .state-card button { border: 0; border-radius: .52rem; padding: .72rem .85rem; background: #1e2761; color: #fff; font-weight: 750; }.preferences .primary { margin-top: 1rem; }.success { padding: .7rem; margin-top: .8rem; border-radius: .5rem; background: #e5f6ec; color: #23754e; font-size: .68rem; }
    .password-form { display: grid; gap: 1rem; padding: 1.15rem; }label { color: #555d72; font-size: .72rem; font-weight: 750; }label input { display: block; width: 100%; margin-top: .4rem; border: 1px solid #d9dde7; border-radius: .52rem; padding: .72rem; }.form-error { padding: .7rem; border-radius: .5rem; background: #fff0ee; color: #a43b2b; font-size: .68rem; }.security-summary { padding: 1.3rem; }.security-icon { width: 3rem; height: 3rem; display: grid; place-items: center; border-radius: .7rem; background: #edf0fb; color: #304b9c; margin-bottom: 1rem; }.security-summary > p { color: #7d8497; font-size: .72rem; line-height: 1.6; }.security-status, .session-row { display: flex; justify-content: space-between; align-items: center; padding: .8rem; margin: 1rem 0; border-radius: .55rem; background: #f6f7fa; color: #777e91; font-size: .68rem; }.security-status strong { color: #936400; }.security-status strong.enabled { color: #23754e; }.security-summary .primary { width: 100%; }.security-summary hr { border: 0; border-top: 1px solid #e7eaf0; margin: 1.2rem 0; }.security-summary > small { color: #989dad; font-size: .62rem; line-height: 1.5; }.state-card { min-height: 250px; display: grid; place-content: center; justify-items: center; text-align: center; background: #fff; border: 1px solid #dfe3ec; border-radius: .8rem; color: #7e8598; }.state-card.error { color: #a43b2b; }
    .modal-backdrop { position: fixed; inset: 0; z-index: 100; display: grid; place-items: center; padding: 1rem; background: rgba(12,18,48,.58); }.mfa-modal { width: min(100%, 430px); background: white; border-radius: .85rem; padding: 1.3rem; }.mfa-modal h2 { margin: 0; color: #29334c; }.mfa-modal > p { color: #7d8497; font-size: .72rem; line-height: 1.6; }.mfa-modal form { display: grid; gap: 1rem; }.mfa-actions { display: flex; justify-content: flex-end; gap: .65rem; }.secondary { border: 1px solid #d8dce6; border-radius: .52rem; padding: .72rem .85rem; background: white; color: #424b63; font-weight: 750; }
    @media (max-width: 800px) { .settings-layout, .security-layout { grid-template-columns: 1fr; } }
  `],
})
export class MerchantSettingsComponent implements OnInit {
  activeTab = signal<'notifications' | 'security'>('notifications'); notifications = signal<MerchantNotification[]>([]); security = signal<MerchantSecuritySummary | null>(null); loading = signal(true); error = signal<string | null>(null);
  preferences: MerchantNotificationPreferences = { email: false, sms: false, push: false, whatsapp: false }; savingPreferences = signal(false); preferenceSuccess = signal(false);
  password = { current: '', next: '', confirm: '' }; savingPassword = signal(false); passwordSuccess = signal(false); savingMfa = signal(false); securityError = signal<string | null>(null);
  showMfaModal = signal(false); mfaDestination = signal('your linked phone'); mfaSetupId = ''; mfaCode = ''; mfaPassword = '';
  constructor(private readonly api: MerchantPortalApiService) {}
  ngOnInit(): void { this.load(); }
  get unreadCount(): number { return this.notifications().filter((notification) => !notification.read).length; }
  load(): void { this.loading.set(true); this.error.set(null); forkJoin({ notifications: this.api.getNotifications(), preferences: this.api.getNotificationPreferences(), security: this.api.getSecuritySummary() }).subscribe({ next: ({ notifications, preferences, security }) => { this.notifications.set(notifications); this.preferences = preferences; this.security.set(security); this.loading.set(false); }, error: (error) => { this.error.set(error?.error?.message ?? 'We could not load your settings.'); this.loading.set(false); } }); }
  readNotification(notification: MerchantNotification): void { if (notification.read) return; this.api.markNotificationRead(notification.id).subscribe({ next: () => this.notifications.update((items) => items.map((item) => item.id === notification.id ? { ...item, read: true } : item)) }); }
  savePreferences(): void { this.savingPreferences.set(true); this.preferenceSuccess.set(false); this.api.updateNotificationPreferences(this.preferences).subscribe({ next: (preferences) => { this.preferences = preferences; this.savingPreferences.set(false); this.preferenceSuccess.set(true); }, error: (error) => { this.error.set(error?.error?.message ?? 'Notification preferences could not be saved.'); this.savingPreferences.set(false); } }); }
  changePassword(): void { this.savingPassword.set(true); this.passwordSuccess.set(false); this.securityError.set(null); this.api.changeMerchantPassword(this.password.current, this.password.next, this.password.confirm).subscribe({ next: () => { this.password = { current: '', next: '', confirm: '' }; this.security.update((value) => value ? { ...value, lastPasswordChange: new Date().toISOString() } : value); this.savingPassword.set(false); this.passwordSuccess.set(true); }, error: (error) => { this.securityError.set(error?.error?.message ?? error?.message ?? 'Your password could not be updated.'); this.savingPassword.set(false); } }); }
  openMfaFlow(): void { const current = this.security(); if (!current) return; this.securityError.set(null); this.mfaCode = ''; this.mfaPassword = ''; if (current.mfaEnabled) { this.showMfaModal.set(true); return; } this.savingMfa.set(true); this.api.beginMerchantMfaSetup().subscribe({ next: (setup) => { this.mfaSetupId = setup.setupId; this.mfaDestination.set(setup.maskedDestination); this.savingMfa.set(false); this.showMfaModal.set(true); }, error: (error) => { this.securityError.set(error?.error?.message ?? 'Two-step verification setup could not be started.'); this.savingMfa.set(false); } }); }
  confirmMfa(): void { const current = this.security(); if (!current) return; this.savingMfa.set(true); this.securityError.set(null); const request = current.mfaEnabled ? this.api.disableMerchantMfa(this.mfaPassword) : this.api.confirmMerchantMfa(this.mfaSetupId, this.mfaCode); request.subscribe({ next: (summary) => { this.security.set(summary); this.savingMfa.set(false); this.closeMfaModal(); }, error: (error) => { this.securityError.set(error?.error?.message ?? error?.message ?? 'Two-step verification could not be updated.'); this.savingMfa.set(false); } }); }
  closeMfaModal(): void { if (!this.savingMfa()) { this.showMfaModal.set(false); this.mfaCode = ''; this.mfaPassword = ''; this.securityError.set(null); } }
  notificationIcon(type: MerchantNotification['type']): string { return ({ PAYMENT: '↗', SETTLEMENT: '↓', SECURITY: '◆', SYSTEM: '!' })[type]; }
}
