import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { MerchantPortalApiService } from '../../core/merchant-portal-api.service';
import { MerchantPortalSessionService } from '../../core/merchant-portal-session.service';
import { MerchantEligibleAccount } from '../../core/models/merchant-portal.models';

@Component({
  selector: 'app-merchant-account-selection',
  standalone: true,
  imports: [CommonModule, RouterLink],
  template: `
    <main class="page"><a class="brand" routerLink="/login/merchants"><span>M</span> MicroBiz Merchants</a><section class="card"><div class="step">Step 5 of 6</div><p class="eyebrow">Merchant account</p><h1>Choose the account for your workspace</h1><p class="subtitle">Only eligible accounts returned after phone verification are shown. Collections and settlements will be linked to the account you confirm here.</p>
      @if (loading()) { <div class="state"><i></i><span>Finding eligible merchant accounts...</span></div> }
      @else if (error()) { <div class="state error"><strong>Accounts unavailable</strong><span>{{ error() }}</span><button (click)="load()">Try again</button></div> }
      @else { <div class="accounts">@for (account of accounts(); track account.fincore_account_id) { <button type="button" class="account" [class.selected]="selected()?.fincore_account_id === account.fincore_account_id" [disabled]="account.status !== 'ACTIVE'" (click)="selected.set(account)"><span class="radio"></span><div><small>{{ account.product_name }}</small><strong>{{ account.account_no }}</strong><em>{{ account.currency }} account · {{ account.status }}</em></div>@if (account.balance !== null) { <b>{{ account.balance | currency:account.currency:'symbol-narrow':'1.2-2' }}</b> }</button> }</div>@if (accounts().length === 0) { <div class="state"><strong>No eligible merchant account</strong><span>Contact MicroBiz support to confirm the product attached to your customer profile.</span></div> }<div class="notice"><strong>Why do I need to choose?</strong><span>Your customer profile may hold several products. This selection prevents payments from being linked to the wrong account.</span></div><button class="continue" type="button" [disabled]="!selected()" (click)="continue()">Confirm account and continue</button> }
      <a class="back" routerLink="/login/merchants/otp">← Back to OTP verification</a>
    </section></main>
  `,
  styles: [`
    :host{display:block;min-height:100vh}.page{min-height:100vh;background:#f5f7fb;padding:2.2rem 1.25rem}.brand{display:flex;align-items:center;gap:.6rem;width:fit-content;margin:0 auto;color:#1e2761;font-weight:800;text-decoration:none}.brand span{width:2rem;height:2rem;display:grid;place-items:center;background:#ffcb45;border-radius:.6rem}.card{position:relative;width:min(100%,620px);margin:3rem auto 0;padding:clamp(1.5rem,5vw,2.6rem);background:white;border:1px solid #e1e5ef;border-radius:1rem;box-shadow:0 18px 55px rgba(30,39,97,.08)}.step{position:absolute;right:1.4rem;top:1.2rem;color:#9298a9;font-size:.7rem}.eyebrow{margin:0;color:#9a6a00;text-transform:uppercase;letter-spacing:.12em;font-size:.66rem;font-weight:850}h1{margin:.5rem 0 .65rem;color:#192250;font-size:1.65rem;letter-spacing:-.035em}.subtitle{margin:0 0 1.5rem;color:#777e92;font-size:.76rem;line-height:1.6}.accounts{display:grid;gap:.7rem}.account{width:100%;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:.8rem;padding:1rem;text-align:left;border:1px solid #dde1ea;border-radius:.7rem;background:white;color:#3f485e}.account.selected{border-color:#334a9b;background:#f7f8ff;box-shadow:0 0 0 2px rgba(51,74,155,.08)}.account:disabled{opacity:.55}.radio{width:1.1rem;height:1.1rem;border:2px solid #b8bfd0;border-radius:50%}.selected .radio{border:4px solid #334a9b}.account div{display:grid;gap:.18rem}.account small{color:#8b92a4;font-size:.6rem}.account strong{color:#303950;font-size:.85rem;letter-spacing:.04em}.account em{color:#7d8497;font-size:.61rem;font-style:normal}.account b{color:#303950;font-size:.75rem}.notice{display:grid;gap:.25rem;margin:1rem 0;padding:.8rem;border-radius:.6rem;background:#fff8e6;color:#74530a}.notice strong{font-size:.68rem}.notice span{font-size:.62rem;line-height:1.5}.continue,.state button{width:100%;border:0;border-radius:.58rem;padding:.82rem;background:#1e2761;color:white;font-weight:750}.continue:disabled{opacity:.5}.back{display:block;margin-top:1rem;text-align:center;color:#697187;font-size:.68rem;text-decoration:none}.state{min-height:160px;display:grid;place-content:center;justify-items:center;gap:.6rem;text-align:center;color:#7d8497}.state i{width:2rem;height:2rem;border:3px solid #e4e7ef;border-top-color:#1e2761;border-radius:50%;animation:spin .75s linear infinite}.state span{font-size:.7rem}.state.error{color:#a43b2b}.state button{width:auto;padding:.55rem .8rem}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:520px){.account{grid-template-columns:auto 1fr}.account b{grid-column:2}}
  `],
})
export class MerchantAccountSelectionComponent implements OnInit {
  accounts = signal<MerchantEligibleAccount[]>([]); selected = signal<MerchantEligibleAccount | null>(null); loading = signal(true); error = signal<string | null>(null);
  constructor(private readonly api: MerchantPortalApiService, private readonly session: MerchantPortalSessionService, private readonly router: Router) {}
  ngOnInit(): void { if (!this.session.accountPreview() || !this.session.otpVerification()?.verification_token || this.session.onboardingStep() !== 'account-selection') { void this.router.navigate(['/login/merchants']); return; } this.load(); }
  load(): void { const preview = this.session.accountPreview(); const token = this.session.otpVerification()?.verification_token; if (!preview || !token) return; this.loading.set(true); this.error.set(null); this.api.getEligibleMerchantAccounts(token, preview).subscribe({ next: (accounts) => { this.accounts.set(accounts); if (accounts.length === 1 && accounts[0].status === 'ACTIVE') this.selected.set(accounts[0]); this.loading.set(false); }, error: (error) => { this.error.set(error?.error?.message ?? error?.message ?? 'Eligible accounts could not be loaded.'); this.loading.set(false); } }); }
  continue(): void { const selected = this.selected(); if (!selected) return; this.session.selectEligibleAccount(selected); void this.router.navigate(['/reg/merchant']); }
}
