import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin } from 'rxjs';
import { MerchantPortalApiService } from '../../core/merchant-portal-api.service';
import { MerchantLocation, MerchantTerminal } from '../../core/models/merchant-portal.models';

@Component({
  selector: 'app-merchant-business',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section class="business-page">
      <header><div><p>Business operations</p><h1>Locations & devices</h1><span>Manage where you operate and monitor assigned payment terminals.</span></div><button type="button" (click)="activeTab() === 'locations' ? openLocationForm() : openTerminalForm()">{{ activeTab() === 'locations' ? '+ Add location' : '+ Request terminal' }}</button></header>
      <nav class="tabs"><button [class.active]="activeTab() === 'locations'" (click)="activeTab.set('locations')">Locations <span>{{ locations().length }}</span></button><button [class.active]="activeTab() === 'terminals'" (click)="activeTab.set('terminals')">Terminals <span>{{ terminals().length }}</span></button></nav>

      @if (loading()) { <div class="state-card">Loading business operations…</div> }
      @else if (error()) { <div class="state-card error"><strong>Business operations unavailable</strong><p>{{ error() }}</p><button (click)="load()">Try again</button></div> }
      @else if (activeTab() === 'locations') {
        @if (locations().length === 0) { <div class="state-card"><strong>No locations yet</strong><p>Add the first location where your business accepts payments.</p><button (click)="openLocationForm()">Add location</button></div> }
        @else { <div class="location-grid">@for (location of locations(); track location.id) { <article class="location-card"><div class="card-heading"><div class="location-mark">⌖</div><span [class]="'status status--' + location.status.toLowerCase()">{{ statusLabel(location.status) }}</span></div><p>{{ location.locationCode }}</p><h2>{{ location.name }}</h2><span class="trading-name">{{ location.tradingName || 'Primary merchant name' }}</span><div class="location-details"><div><small>Address</small><strong>{{ location.address }}</strong></div><div><small>Area</small><strong>{{ location.localGovernment || '—' }}{{ location.state ? ', ' + location.state : '' }}</strong></div><div><small>Contact</small><strong>{{ location.contactPerson || 'Not assigned' }}</strong></div><div><small>Operating hours</small><strong>{{ location.operatingHours || 'Not supplied' }}</strong></div></div><footer><span>{{ terminalCount(location.id) }} terminal{{ terminalCount(location.id) === 1 ? '' : 's' }}</span><button type="button" (click)="requestForLocation(location.id)">Request device</button></footer></article> }</div> }
      } @else {
        @if (terminals().length === 0) { <div class="state-card"><strong>No terminals assigned</strong><p>Request a payment device for one of your locations.</p><button (click)="openTerminalForm()">Request terminal</button></div> }
        @else { <section class="terminal-card"><div class="responsive-table"><table><thead><tr><th>Terminal</th><th>Device</th><th>Location</th><th>Status</th><th>Last heartbeat</th><th>Last transaction</th></tr></thead><tbody>@for (terminal of terminals(); track terminal.id) { <tr><td><strong>{{ terminal.terminalId }}</strong><small>{{ terminal.serialNumber }}</small></td><td>{{ terminal.model || terminal.terminalType }}<small>{{ terminal.applicationVersion ? 'App ' + terminal.applicationVersion : terminal.provider }}</small></td><td>{{ locationName(terminal.locationId) }}</td><td><span [class]="'status status--' + terminal.status.toLowerCase().replace('_', '-')">{{ statusLabel(terminal.status) }}</span></td><td>{{ terminal.lastHeartbeatAt ? (terminal.lastHeartbeatAt | date:'dd MMM, HH:mm') : 'Not available' }}</td><td>{{ terminal.lastTransactionAt ? (terminal.lastTransactionAt | date:'dd MMM, HH:mm') : 'No activity' }}</td></tr> }</tbody></table></div></section> }
      }

      @if (showLocationForm()) { <div class="modal-backdrop" (click)="closeForms()"><section class="modal" (click)="$event.stopPropagation()"><div class="modal-heading"><div><p>New business location</p><h2>Add a location</h2></div><button type="button" (click)="closeForms()">×</button></div><form (ngSubmit)="createLocation()" #locationFormRef="ngForm"><div class="field-grid"><label>Location name<input name="locationName" [(ngModel)]="locationForm.name" required maxlength="255" /></label><label>Trading name <small>Optional</small><input name="tradingName" [(ngModel)]="locationForm.trading_name" maxlength="255" /></label><label class="wide">Address<textarea name="address" [(ngModel)]="locationForm.address" required rows="3"></textarea></label><label>State<input name="state" [(ngModel)]="locationForm.state" /></label><label>Local government<input name="localGovernment" [(ngModel)]="locationForm.local_government" /></label><label>Contact person<input name="contactPerson" [(ngModel)]="locationForm.contact_person" /></label><label>Operating hours<input name="operatingHours" [(ngModel)]="locationForm.operating_hours" placeholder="Mon-Sat, 8:00-20:00" /></label></div>@if (formError()) { <div class="form-error">{{ formError() }}</div> }<div class="actions"><button class="secondary" type="button" (click)="closeForms()">Cancel</button><button type="submit" [disabled]="locationFormRef.invalid || saving()">{{ saving() ? 'Adding location…' : 'Add location' }}</button></div></form></section></div> }

      @if (showTerminalForm()) { <div class="modal-backdrop" (click)="closeForms()"><section class="modal" (click)="$event.stopPropagation()"><div class="modal-heading"><div><p>Payment device</p><h2>Request terminals</h2></div><button type="button" (click)="closeForms()">×</button></div><form (ngSubmit)="requestTerminal()" #terminalFormRef="ngForm"><label>Terminal type<select name="terminalType" [(ngModel)]="terminalForm.terminal_type" required><option value="ANDROID_POS">Android POS</option><option value="MPOS">Mobile POS</option><option value="QR_STAND">QR display stand</option></select></label><label>Business location<select name="terminalLocation" [(ngModel)]="terminalForm.merchant_location_id"><option [ngValue]="null">Assign later</option>@for (location of locations(); track location.id) { <option [ngValue]="location.id">{{ location.name }}</option> }</select></label><label>Quantity<input type="number" name="quantity" [(ngModel)]="terminalForm.quantity" required min="1" max="10" /></label><label>Request notes <small>Optional</small><textarea name="terminalNotes" [(ngModel)]="terminalForm.notes" rows="3"></textarea></label><p class="request-note">MicroBiz operations will review the request, assign device identifiers, and manage activation. Merchants cannot self-activate terminals.</p>@if (formError()) { <div class="form-error">{{ formError() }}</div> }<div class="actions"><button class="secondary" type="button" (click)="closeForms()">Cancel</button><button type="submit" [disabled]="terminalFormRef.invalid || saving()">{{ saving() ? 'Submitting request…' : 'Submit request' }}</button></div></form></section></div> }
    </section>
  `,
  styles: [`
    .business-page { display: grid; gap: 1.25rem; }header { display: flex; justify-content: space-between; align-items: end; gap: 1rem; }header p, .modal-heading p { text-transform: uppercase; color: #a06e00; letter-spacing: .11em; font-size: .7rem; font-weight: 800; margin: 0; }header h1 { color: #182250; font-size: 2rem; letter-spacing: -.04em; margin: .25rem 0; }header span { color: #7e8497; font-size: .85rem; }header > button, .actions button, .state-card button { border: 0; border-radius: .55rem; padding: .72rem .9rem; background: #1e2761; color: white; font-weight: 750; }
    .tabs { display: flex; gap: .35rem; border-bottom: 1px solid #dfe3ec; }.tabs button { border: 0; background: transparent; padding: .75rem .85rem; color: #757c90; font-weight: 700; border-bottom: 2px solid transparent; }.tabs button.active { color: #1e2761; border-bottom-color: #1e2761; }.tabs span { margin-left: .3rem; padding: .15rem .35rem; border-radius: 1rem; background: #e9ecf5; font-size: .65rem; }
    .location-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 1rem; }.location-card { background: #fff; border: 1px solid #dfe3ec; border-radius: .8rem; padding: 1.1rem; }.card-heading { display: flex; justify-content: space-between; align-items: center; }.location-mark { width: 2.4rem; height: 2.4rem; display: grid; place-items: center; border-radius: .6rem; background: #edf0fb; color: #304b9c; }.location-card > p { color: #989dad; font-size: .65rem; margin: .85rem 0 .2rem; }.location-card h2 { color: #303950; margin: 0; font-size: 1rem; }.trading-name { color: #80879a; font-size: .72rem; }.location-details { display: grid; grid-template-columns: 1fr 1fr; gap: .8rem; padding: 1rem 0; margin-top: 1rem; border-top: 1px solid #eceef3; }.location-details div { display: grid; gap: .22rem; }.location-details small { color: #989dad; font-size: .62rem; }.location-details strong { color: #50586e; font-size: .72rem; }.location-card footer { display: flex; justify-content: space-between; align-items: center; padding-top: .75rem; border-top: 1px solid #eceef3; color: #83899b; font-size: .68rem; }.location-card footer button { border: 0; background: transparent; color: #2e4798; font-weight: 750; }
    .terminal-card { background: white; border: 1px solid #dfe3ec; border-radius: .8rem; overflow: hidden; }.responsive-table { overflow-x: auto; }table { min-width: 850px; }th { background: #fafbfc; font-size: .65rem; }td { color: #687084; font-size: .75rem; }td strong, td small { display: block; }td strong { color: #303950; }td small { margin-top: .2rem; color: #989dad; font-size: .65rem; }.status { display: inline-block; border-radius: 1rem; padding: .25rem .5rem; font-size: .6rem; font-weight: 800; }.status--active { color: #23754e; background: #e3f5eb; }.status--suspended { color: #aa4232; background: #fde9e5; }.status--requested, .status--pending-activation { color: #936400; background: #fff2ce; }
    .state-card { min-height: 250px; display: grid; place-content: center; justify-items: center; text-align: center; background: white; border: 1px solid #dfe3ec; border-radius: .8rem; color: #7e8598; }.state-card p { font-size: .78rem; }.state-card.error { color: #a43b2b; }
    .modal-backdrop { position: fixed; inset: 0; z-index: 100; display: grid; place-items: center; padding: 1rem; background: rgba(12,18,48,.58); }.modal { width: min(100%, 620px); max-height: calc(100vh - 2rem); overflow-y: auto; background: #fff; border-radius: .9rem; padding: 1.35rem; }.modal-heading { display: flex; justify-content: space-between; gap: 1rem; margin-bottom: 1.2rem; }.modal-heading h2 { margin: .3rem 0 0; color: #29334c; }.modal-heading > button { border: 0; background: transparent; font-size: 1.4rem; color: #7c8396; }.modal form { display: grid; gap: 1rem; }.field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }.wide { grid-column: 1 / -1; }label { color: #555d72; font-size: .72rem; font-weight: 750; }label small { color: #9a9faf; font-weight: 500; }input, textarea, select { display: block; width: 100%; margin-top: .4rem; border: 1px solid #d9dde7; border-radius: .52rem; padding: .72rem; background: white; color: #343d54; outline: 0; }.actions { display: flex; justify-content: flex-end; gap: .65rem; }.actions button:disabled { opacity: .55; cursor: not-allowed; }.secondary { background: white !important; color: #424b63 !important; border: 1px solid #d8dce6 !important; }.form-error { padding: .7rem; border-radius: .5rem; background: #fff0ee; color: #a43b2b; font-size: .7rem; }.request-note { color: #858b9c; background: #f5f7fa; padding: .75rem; border-radius: .5rem; font-size: .68rem; line-height: 1.55; }
    @media (max-width: 760px) { .location-grid { grid-template-columns: 1fr; }.field-grid { grid-template-columns: 1fr; }.wide { grid-column: auto; } }
    @media (max-width: 540px) { header { align-items: start; flex-direction: column; }.tabs { overflow-x: auto; overscroll-behavior-inline: contain; }.tabs button { flex: 0 0 auto; white-space: nowrap; }.location-details { grid-template-columns: 1fr; }.location-footer { align-items: flex-start; flex-direction: column; }.actions { flex-direction: column-reverse; }.actions button { width: 100%; } }
  `],
})
export class MerchantBusinessComponent implements OnInit {
  activeTab = signal<'locations' | 'terminals'>('locations'); locations = signal<MerchantLocation[]>([]); terminals = signal<MerchantTerminal[]>([]);
  loading = signal(true); saving = signal(false); error = signal<string | null>(null); formError = signal<string | null>(null); showLocationForm = signal(false); showTerminalForm = signal(false);
  locationForm = { name: '', trading_name: '', address: '', state: '', local_government: '', contact_person: '', operating_hours: '' };
  terminalForm = { terminal_type: 'ANDROID_POS', merchant_location_id: null as number | null, quantity: 1, notes: '' };
  constructor(private readonly api: MerchantPortalApiService) {}
  ngOnInit(): void { this.load(); }
  load(): void { this.loading.set(true); this.error.set(null); forkJoin({ locations: this.api.getLocations(), terminals: this.api.getTerminals() }).subscribe({ next: ({ locations, terminals }) => { this.locations.set(locations); this.terminals.set(terminals); this.loading.set(false); }, error: (error) => { this.error.set(error?.error?.message ?? 'We could not load your locations and devices.'); this.loading.set(false); } }); }
  openLocationForm(): void { this.formError.set(null); this.showLocationForm.set(true); }
  openTerminalForm(): void { this.formError.set(null); this.showTerminalForm.set(true); }
  requestForLocation(locationId: number): void { this.terminalForm.merchant_location_id = locationId; this.activeTab.set('terminals'); this.openTerminalForm(); }
  closeForms(): void { if (!this.saving()) { this.showLocationForm.set(false); this.showTerminalForm.set(false); this.formError.set(null); } }
  createLocation(): void { this.saving.set(true); this.formError.set(null); this.api.createLocation({ name: this.locationForm.name.trim(), trading_name: this.locationForm.trading_name.trim() || undefined, address: this.locationForm.address.trim(), state: this.locationForm.state.trim() || undefined, local_government: this.locationForm.local_government.trim() || undefined, contact_person: this.locationForm.contact_person.trim() || undefined, operating_hours: this.locationForm.operating_hours.trim() || undefined }).subscribe({ next: (location) => { this.locations.update((items) => [location, ...items]); this.locationForm = { name: '', trading_name: '', address: '', state: '', local_government: '', contact_person: '', operating_hours: '' }; this.saving.set(false); this.showLocationForm.set(false); }, error: (error) => { this.formError.set(error?.error?.message ?? 'The location could not be added.'); this.saving.set(false); } }); }
  requestTerminal(): void { this.saving.set(true); this.formError.set(null); this.api.requestTerminal({ terminal_type: this.terminalForm.terminal_type, merchant_location_id: this.terminalForm.merchant_location_id ?? undefined, quantity: this.terminalForm.quantity, notes: this.terminalForm.notes.trim() || undefined }).subscribe({ next: (terminal) => { this.terminals.update((items) => [terminal, ...items]); this.terminalForm = { terminal_type: 'ANDROID_POS', merchant_location_id: null, quantity: 1, notes: '' }; this.saving.set(false); this.showTerminalForm.set(false); this.activeTab.set('terminals'); }, error: (error) => { this.formError.set(error?.error?.message ?? 'The terminal request could not be submitted.'); this.saving.set(false); } }); }
  terminalCount(locationId: number): number { return this.terminals().filter((terminal) => terminal.locationId === locationId).length; }
  locationName(locationId: number | null): string { return this.locations().find((location) => location.id === locationId)?.name ?? 'Not assigned'; }
  statusLabel(status: string): string { return status.split('_').map((word) => word.charAt(0) + word.slice(1).toLowerCase()).join(' '); }
}
