import { CommonModule } from '@angular/common';
import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MerchantPortalApiService } from '../../core/merchant-portal-api.service';
import { MerchantSupportTicket } from '../../core/models/merchant-portal.models';

@Component({
  selector: 'app-merchant-support',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section class="support-page">
      <header><div><p>Help centre</p><h1>Merchant support</h1><span>Track existing cases or tell us how we can help.</span></div><button type="button" (click)="showForm.set(true)">+ Open support ticket</button></header>
      <div class="contact-grid"><article><span>✉</span><div><small>Email support</small><strong>support&#64;microbiz.test</strong></div></article><article><span>☎</span><div><small>Merchant support line</small><strong>Available 08:00–20:00</strong></div></article><article><span>◷</span><div><small>Typical response</small><strong>Within 4 business hours</strong></div></article></div>
      <section class="tickets-card"><div class="card-heading"><div><h2>Your support tickets</h2><p>Updates from the merchant operations team.</p></div><select [(ngModel)]="statusFilter"><option value="">All tickets</option><option value="OPEN">Open</option><option value="IN_PROGRESS">In progress</option><option value="RESOLVED">Resolved</option><option value="CLOSED">Closed</option></select></div>
        @if (loading()) { <div class="state">Loading support tickets…</div> }
        @else if (error()) { <div class="state error"><strong>Support tickets unavailable</strong><p>{{ error() }}</p><button (click)="load()">Try again</button></div> }
        @else if (filteredTickets.length === 0) { <div class="state"><strong>No support tickets</strong><p>When you contact support, your cases will appear here.</p></div> }
        @else { <div class="ticket-list">@for (ticket of filteredTickets; track ticket.id) { <button type="button" class="ticket-row" (click)="toggleTicket(ticket)"><span class="ticket-icon">{{ categoryIcon(ticket.category) }}</span><div><strong>{{ ticket.subject }}</strong><small>{{ ticket.ticketNo }} · {{ categoryLabel(ticket.category) }}</small></div><span [class]="'priority priority--' + ticket.priority.toLowerCase()">{{ ticket.priority }}</span><span [class]="'status status--' + ticket.status.toLowerCase()">{{ statusLabel(ticket.status) }}</span><time>{{ ticket.updatedAt | date:'dd MMM yyyy' }}</time></button>@if (selected()?.id === ticket.id) { <div class="ticket-detail"><p>{{ ticket.description }}</p><div><span>Created {{ ticket.createdAt | date:'medium' }}</span><span>Last updated {{ ticket.updatedAt | date:'medium' }}</span></div></div> } }</div> }
      </section>
      @if (success()) { <div class="toast">✓ Support ticket {{ success()?.ticketNo }} was created.</div> }
      @if (showForm()) { <div class="modal-backdrop" (click)="closeForm()"><section class="modal" (click)="$event.stopPropagation()"><div class="modal-heading"><div><p>Contact support</p><h2>Open a support ticket</h2></div><button type="button" (click)="closeForm()">×</button></div><form (ngSubmit)="submit()" #supportForm="ngForm"><label>Category<select name="category" [(ngModel)]="form.category" required><option value="PAYMENT">Payment or transaction</option><option value="SETTLEMENT">Settlement</option><option value="TERMINAL">Terminal or device</option><option value="ACCOUNT">Account and profile</option><option value="OTHER">Other</option></select></label><label>Priority<select name="priority" [(ngModel)]="form.priority" required><option value="LOW">Low</option><option value="MEDIUM">Medium</option><option value="HIGH">High</option></select></label><label class="wide">Subject<input name="subject" [(ngModel)]="form.subject" required maxlength="255" /></label><label class="wide">Describe the issue<textarea name="description" [(ngModel)]="form.description" required minlength="10" maxlength="2000" rows="6"></textarea><small class="field-hint">At least 10 characters.</small></label>@if (formError()) { <div class="form-error wide">{{ formError() }}</div> }<div class="actions wide"><button class="secondary" type="button" (click)="closeForm()">Cancel</button><button type="submit" [disabled]="supportForm.invalid || saving()">{{ saving() ? 'Submitting ticket…' : 'Submit ticket' }}</button></div></form></section></div> }
    </section>
  `,
  styles: [`
    .support-page { display: grid; gap: 1.25rem; }header { display: flex; justify-content: space-between; align-items: end; gap: 1rem; }header p, .modal-heading p { text-transform: uppercase; color: #a06e00; letter-spacing: .11em; font-size: .7rem; font-weight: 800; margin: 0; }header h1 { color: #182250; font-size: 2rem; letter-spacing: -.04em; margin: .25rem 0; }header span { color: #7e8497; font-size: .85rem; }header > button, .actions button, .state button { border: 0; border-radius: .55rem; padding: .72rem .9rem; background: #1e2761; color: #fff; font-weight: 750; }.contact-grid { display: grid; grid-template-columns: repeat(3,1fr); gap: 1rem; }.contact-grid article { display: flex; align-items: center; gap: .75rem; padding: 1rem; background: #fff; border: 1px solid #dfe3ec; border-radius: .7rem; }.contact-grid article > span { width: 2.2rem; height: 2.2rem; display: grid; place-items: center; border-radius: .55rem; background: #edf0fb; color: #304b9c; }.contact-grid div { display: grid; gap: .2rem; }.contact-grid small { color: #969cad; font-size: .65rem; }.contact-grid strong { color: #3a4359; font-size: .75rem; }
    .tickets-card { background: #fff; border: 1px solid #dfe3ec; border-radius: .8rem; overflow: hidden; }.card-heading { display: flex; justify-content: space-between; align-items: center; gap: 1rem; padding: 1rem 1.15rem; border-bottom: 1px solid #e9ecf2; }.card-heading h2 { margin: 0 0 .25rem; color: #303950; font-size: 1rem; }.card-heading p { margin: 0; color: #8b91a3; font-size: .7rem; }.card-heading select { border: 1px solid #d9dde7; border-radius: .5rem; padding: .55rem; background: white; }.ticket-row { width: 100%; display: grid; grid-template-columns: auto 1fr auto auto auto; align-items: center; gap: .8rem; text-align: left; padding: .9rem 1.1rem; border: 0; border-bottom: 1px solid #eceef3; background: #fff; }.ticket-row:hover { background: #fafbfe; }.ticket-icon { width: 2rem; height: 2rem; display: grid; place-items: center; border-radius: .5rem; background: #f0f2f8; }.ticket-row div { display: grid; gap: .2rem; }.ticket-row strong { color: #343d54; font-size: .78rem; }.ticket-row small, .ticket-row time { color: #9399aa; font-size: .65rem; }.priority, .status { padding: .24rem .45rem; border-radius: 1rem; font-size: .58rem; font-weight: 800; }.priority--high { color: #aa4232; background: #fde9e5; }.priority--medium { color: #936400; background: #fff2ce; }.priority--low { color: #30669a; background: #e8f2fb; }.status--open, .status--in_progress { color: #936400; background: #fff2ce; }.status--resolved, .status--closed { color: #23754e; background: #e3f5eb; }.ticket-detail { padding: 1rem 1.2rem; background: #f7f8fc; border-bottom: 1px solid #e7eaf1; }.ticket-detail p { color: #5f677b; font-size: .75rem; line-height: 1.6; }.ticket-detail div { display: flex; gap: 1rem; color: #989dad; font-size: .62rem; }.state { min-height: 230px; display: grid; place-content: center; justify-items: center; text-align: center; color: #7e8598; }.state p { font-size: .75rem; }.state.error { color: #a43b2b; }
    .modal-backdrop { position: fixed; inset: 0; z-index: 100; display: grid; place-items: center; padding: 1rem; background: rgba(12,18,48,.58); }.modal { width: min(100%, 650px); background: #fff; border-radius: .9rem; padding: 1.35rem; }.modal-heading { display: flex; justify-content: space-between; margin-bottom: 1.2rem; }.modal-heading h2 { margin: .3rem 0 0; color: #29334c; }.modal-heading > button { border: 0; background: transparent; font-size: 1.4rem; }.modal form { display: grid; grid-template-columns: 1fr 1fr; gap: 1rem; }.wide { grid-column: 1 / -1; }label { color: #555d72; font-size: .72rem; font-weight: 750; }input, textarea, select { display: block; width: 100%; margin-top: .4rem; border: 1px solid #d9dde7; border-radius: .52rem; padding: .72rem; background: white; color: #343d54; }.field-hint { display: block; margin: .4rem 0 0 !important; color: #9a9fb0; font-size: .61rem; font-weight: 500; }.actions { display: flex; justify-content: flex-end; gap: .65rem; }.actions button:disabled { opacity: .55; cursor: not-allowed; }.secondary { background: white !important; color: #424b63 !important; border: 1px solid #d8dce6 !important; }.form-error { padding: .7rem; border-radius: .5rem; background: #fff0ee; color: #a43b2b; font-size: .7rem; }.toast { position: fixed; right: 1.5rem; bottom: 1.5rem; z-index: 120; padding: .8rem 1rem; border-radius: .55rem; background: #23754e; color: white; font-size: .72rem; }
    @media (max-width: 760px) { .contact-grid { grid-template-columns: 1fr; }.ticket-row { grid-template-columns: auto 1fr auto; }.ticket-row .priority, .ticket-row time { display: none; } }
    @media (max-width: 540px) { header { align-items: start; flex-direction: column; }.card-heading { align-items: start; flex-direction: column; }.modal form { grid-template-columns: 1fr; }.wide { grid-column: auto; }.actions { flex-direction: column-reverse; }.actions button { width: 100%; } }
  `],
})
export class MerchantSupportComponent implements OnInit {
  tickets = signal<MerchantSupportTicket[]>([]); selected = signal<MerchantSupportTicket | null>(null); loading = signal(true); saving = signal(false); showForm = signal(false); error = signal<string | null>(null); formError = signal<string | null>(null); success = signal<MerchantSupportTicket | null>(null); statusFilter = '';
  form = { category: 'PAYMENT', priority: 'MEDIUM', subject: '', description: '' };
  constructor(private readonly api: MerchantPortalApiService) {}
  ngOnInit(): void { this.load(); }
  get filteredTickets(): MerchantSupportTicket[] { return this.tickets().filter((ticket) => !this.statusFilter || ticket.status === this.statusFilter); }
  load(): void { this.loading.set(true); this.error.set(null); this.api.getSupportTickets().subscribe({ next: (tickets) => { this.tickets.set(tickets); this.loading.set(false); }, error: (error) => { this.error.set(error?.error?.message ?? 'We could not load your support tickets.'); this.loading.set(false); } }); }
  submit(): void { this.saving.set(true); this.formError.set(null); this.api.createSupportTicket({ ...this.form }).subscribe({ next: (ticket) => { this.tickets.update((items) => [ticket, ...items]); this.success.set(ticket); this.form = { category: 'PAYMENT', priority: 'MEDIUM', subject: '', description: '' }; this.saving.set(false); this.showForm.set(false); window.setTimeout(() => this.success.set(null), 4500); }, error: (error) => { this.formError.set(error?.error?.message ?? 'The support ticket could not be submitted.'); this.saving.set(false); } }); }
  closeForm(): void { if (!this.saving()) { this.showForm.set(false); this.formError.set(null); } }
  toggleTicket(ticket: MerchantSupportTicket): void { this.selected.set(this.selected()?.id === ticket.id ? null : ticket); }
  categoryLabel(category: string): string { return category.charAt(0) + category.slice(1).toLowerCase(); }
  categoryIcon(category: string): string { return ({ PAYMENT: '↗', SETTLEMENT: '↓', TERMINAL: '▣', ACCOUNT: '○', OTHER: '?' } as Record<string,string>)[category] ?? '?'; }
  statusLabel(status: string): string { return status.split('_').map((word) => word.charAt(0) + word.slice(1).toLowerCase()).join(' '); }
}
