export const environment = {
  production: false,
  apiUrl: '/api',
  merchantPortalApiMode: 'live' as 'mock' | 'live',
  merchantPortalLiveFeatures: {
    accountPreview: true,
    otp: false,
    registration: false,
    merchantProfile: false,
    merchantSession: false,
    merchantDashboard: false,
    merchantTransactions: false,
    merchantCollections: false,
    merchantSettlements: false,
    merchantBusiness: false,
    merchantSupport: false,
    merchantSettings: false,
    merchantReports: false,
    merchantPaymentTools: false,
    merchantOperations: false,
  },
};
